# Generated by Django 5.2.4 on 2025-07-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('ACCT', 'ACCT'), ('STAFF', 'STAFF')], null=True),
        ),
    ]
